### ISSUE TITLE
[REQUEST] Multiple models selection menu

### ISSUE THREAD

**Issue by Steffion** [TheCodingBeast/TCB_F4Menu#1]
Hello TheCodingBeast,

I would like to have a feature were you can choose what model of a list of models you can become.
Because now you can't choose a model. It will use the first one in the models list.

Could you fix this?
Thanks in advance!

Yours sincerely,
Steffion

**Comment by Prepager** [comment]
I will take a look at that at some point.

**Comment by UltimateByte** [comment]
+1 for this, this is crucial.
