### ISSUE TITLE
Food won't appear

### ISSUE THREAD

**Issue by UltimateByte** [TheCodingBeast/TCB_F4Menu#2]
This is a highly critical issue. Entities Food included in DarkRP won't appear into your F4 Menu. Those who want to use food mod with your F4 menu just can't.

**Comment by Prepager** [comment]
Because the F4 menu don't support hungermod.

**Comment by UltimateByte** [comment]
Any chance for you to include food into your F4 Menu ?
Otherwise i have to say it's great !
