### ISSUE TITLE
A way to add more commands

### ISSUE THREAD

**Issue by UltimateByte** [TheCodingBeast/TCB_F4Menu#4]
Could you please give a way to add more commands without modifying the whole LUA code, like into the sh_config.lua ?

**Comment by Prepager** [comment]
https://github.com/TheCodingBeast/TCB_F4Menu/blob/master/tcb_f4menu/cl_panel_commands.lua#L12-L52 Won't get any easier than that.

**Comment by UltimateByte** [comment]
Woh yeah, pardon my ignorance.
